language: java
dist: trusty
before_script: cd api/
script: mvn test -Ptest -DskipTests=false -Dhttps.protocols=TLSv1.2 -DmessageBirdAccessKey=test_iQpAp0KCs5GCsMpDhIx2leuNB -DmessageBirdMSISDN=31612345678
jdk:
  - oraclejdk11
  - openjdk11
